// Leadgen — Ad Verification (warm-gated 'ads' fleet service). Active-Ad Detection Tier 2 / CONFIRMED.
// Deployed instance: <<WORKFLOW_ID>>.
// Claim 'ads' -> Get Target (business_name + website_domain) -> Meta Ad Library API (active
// creatives by name) + SerpApi google_ads_transparency_center (by domain) -> Build Evidence:
// ad_status {overall_is_advertising, tier:'CONFIRMED'|'checked', summary:{meta,google}, evidence_
// ledger:{live_ad_urls}} + ad_active (boolean) -> complete_analysis_work_item (cause ads_evidence)
// -> re-score. GATING: created 'blocked' at discovery; the Scorer opens it (blocked->pending) only
// when the lead is warm/hot (complete_scorer_work_item ads gate). Ships behind service_config.ads.
// SECRETS: Meta Ad Library token inline in the Meta node (redacted <<META_TOKEN>> here); SerpApi via
// the "SerpApi account" credential. Yelp (SerpApi) + Nextdoor (Apify) are documented v2 additions.
import { workflow, node, trigger, sticky, newCredential, expr } from '@n8n/workflow-sdk';

const everyMinute = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.3, config: { name: 'Poll Ads Queue', position: [200, 240], parameters: { rule: { interval: [{ field: 'minutes', minutesInterval: 1 }] } } }, output: [{}] });
const poke = trigger({ type: 'n8n-nodes-base.webhook', version: 2.1, config: { name: 'Ads Poke', position: [200, 440], parameters: { httpMethod: 'POST', path: 'leadgen-ads-poke', responseMode: 'onReceived' } }, output: [{ body: {} }] });

const claim = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Claim Ads Work', position: [460, 320], executeOnce: true, parameters: { operation: 'executeQuery', query: "SELECT work_item_id, claim_token, service_run_id, campaign_id, campaign_lead_id FROM leadgen.claim_work_items('ads', $1)", options: { queryReplacement: expr('ads-{{ $execution.id }}') } }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ work_item_id: 'wi', claim_token: 'ct', campaign_id: 'c', campaign_lead_id: 'l' }] });

const getTarget = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Get Target', position: [720, 320], parameters: { operation: 'executeQuery', query: "SELECT b.id AS business_id, b.business_name, b.website_domain FROM leadgen.campaign_leads cl JOIN leadgen.businesses b ON b.id=cl.business_id WHERE cl.id=$1", options: { queryReplacement: expr('{{ $json.campaign_lead_id }}') } }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ business_id: 'b', business_name: 'X', website_domain: 'x.com' }] });

const metaAdLib = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Meta Ad Library', position: [980, 220], onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 2000, parameters: { method: 'GET', url: 'https://graph.facebook.com/v21.0/ads_archive', sendQuery: true, specifyQuery: 'keypair', queryParameters: { parameters: [ { name: 'search_terms', value: expr('{{ $json.business_name }}') }, { name: 'ad_reached_countries', value: '["US"]' }, { name: 'ad_active_status', value: 'ACTIVE' }, { name: 'fields', value: 'id,page_name,ad_snapshot_url' }, { name: 'limit', value: '10' }, { name: 'access_token', value: '<<META_TOKEN>>' } ] }, options: { timeout: 30000 } } }, output: [{ data: [] }] });

const googTransparency = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Google Transparency', position: [980, 420], onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 2500, parameters: { method: 'GET', url: 'https://serpapi.com/search.json', authentication: 'predefinedCredentialType', nodeCredentialType: 'serpApi', sendQuery: true, specifyQuery: 'keypair', queryParameters: { parameters: [ { name: 'engine', value: 'google_ads_transparency_center' }, { name: 'text', value: expr("{{ $('Get Target').item.json.website_domain || $('Get Target').item.json.business_name }}") } ] }, options: { timeout: 30000 } }, credentials: { serpApi: newCredential('SerpApi account') } }, output: [{ ad_creatives: [] }] });

const buildEvidence = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Build Ads Evidence', position: [1240, 320], parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const B=$('Get Target').item.json; const meta=$('Meta Ad Library').item.json||{}; const goog=$('Google Transparency').item.json||{}; const nm=((B.business_name||'')+'').toLowerCase(); const firstWord=nm.split(' ')[0]||''; const metaAds=Array.isArray(meta.data)?meta.data:[]; const metaMatch=metaAds.filter(function(a){ if(!a) return false; var pn=((a.page_name||'')+'').toLowerCase(); return !firstWord || pn.indexOf(firstWord)>=0; }); const metaConfirmed=metaMatch.length>0; var metaUrls=[]; for(var i=0;i<metaMatch.length && metaUrls.length<3;i++){ if(metaMatch[i].ad_snapshot_url) metaUrls.push(metaMatch[i].ad_snapshot_url); } const googCreatives=Array.isArray(goog.ad_creatives)?goog.ad_creatives:(Array.isArray(goog.ads)?goog.ads:[]); const googConfirmed=googCreatives.length>0; var googUrl=(goog.search_metadata&&(goog.search_metadata.google_ads_transparency_center_url||goog.search_metadata.url))||null; var liveUrls=metaUrls.slice(); if(googUrl) liveUrls.push(googUrl); const anyConf=metaConfirmed||googConfirmed; const ad_status={ overall_is_advertising:anyConf, tier:(anyConf?'CONFIRMED':'checked'), summary:{ meta:(metaConfirmed?'CONFIRMED':'NONE'), google:(googConfirmed?'CONFIRMED':'NONE') }, evidence_ledger:{ live_ad_urls:liveUrls } }; const evidence=[ { feature_key:'ad_status', value:ad_status, value_type:'object', product_tag:'ads_video', source_provider:'ad_verification', idempotency_key:B.business_id+':ad_status' }, { feature_key:'ad_active', value:anyConf, value_type:'boolean', product_tag:'ads_video', source_provider:'ad_verification', idempotency_key:B.business_id+':ad_active' } ]; return { json:{ payload:{ evidence:evidence, cause_type:'ads_evidence', run:{ workflow_version:'ads-v1' } } } };" } }, output: [{ payload: {} }] });

const complete = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Complete Ads', position: [1500, 320], parameters: { operation: 'executeQuery', query: "=SELECT leadgen.complete_analysis_work_item('{{ $('Claim Ads Work').item.json.work_item_id }}'::uuid, '{{ $('Claim Ads Work').item.json.claim_token }}'::uuid, '{{ JSON.stringify($json.payload).replace(/'/g, \"''\") }}'::jsonb) AS result" }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ result: {} }] });

const note = sticky('## Ad Verification (warm-gated `ads` service — Tier 2 CONFIRMED)\n\nClaim ads -> Get Target -> Meta Ad Library API (active creatives by name) + SerpApi google_ads_transparency_center (by domain) -> ad_status {tier CONFIRMED, summary{meta,google}, live_ad_urls} + ad_active -> complete_analysis_work_item (cause ads_evidence) -> re-score. Gated to warm/hot by the Scorer; behind service_config.ads.enabled. Meta token inline (redacted); SerpApi via credential. v2: Yelp (SerpApi) + Nextdoor (Apify).', [claim], { color: 5 });

export default workflow('leadgen-ads-verification', 'Leadgen — Ad Verification')
  .add(everyMinute).to(claim)
  .add(poke).to(claim)
  .add(claim).to(getTarget).to(metaAdLib).to(googTransparency).to(buildEvidence).to(complete)
  .add(note);
