// Leadgen — Competitor Gap-Finder (warm-gated 'competitors' fleet service).
// Deployed instance: <<WORKFLOW_ID>>.
// Claim 'competitors' -> Get Target (name, domain, address, lat/lng, place_id, campaign category +
// latest rating/review_volume evidence) -> Google Places Text Search (same category, locationBias circle
// around the target) -> Rank Competitors (exclude the target, require >=15 reviews, score = rating x
// ln(1+reviews), pick the single best + 2 runners-up) -> deep-dive the BEST rival's live ads (Meta Ad
// Library + SerpApi Google/Yelp transparency, reusing the hardened all-token matcher) -> Build
// competitor_set evidence {target{rating,reviews}, best{name,rating,reviews,website,ads{summary,
// confirmed,live_ad_urls}}, others[]} -> complete_analysis_work_item (cause competitors_evidence) ->
// re-score. The Report renders this as a "How you stack up" side-by-side. GATING: created 'blocked' at
// discovery; the Scorer opens it (blocked->pending) only when the lead is warm/hot
// (complete_scorer_work_item competitors gate). Ships behind service_config.competitors.
//
// HONESTY: named-competitor ad claims are CONFIRMED-only (same all-token matcher as ad verification) so
// the report never states a named rival "runs ads" off a competitor bidding on the same search term.
// SECRETS: Meta Ad Library token inline in the Comp Meta node (redacted <<META_TOKEN>> here); SerpApi via
// the "SerpApi account" credential; Places via the "Google Places API" HTTP Header Auth credential.
import { workflow, node, trigger, sticky, newCredential, expr } from '@n8n/workflow-sdk';

const everyMinute = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.3, config: { name: 'Poll Competitors Queue', position: [200, 240], parameters: { rule: { interval: [{ field: 'minutes', minutesInterval: 1 }] } } }, output: [{}] });
const poke = trigger({ type: 'n8n-nodes-base.webhook', version: 2.1, config: { name: 'Competitors Poke', position: [200, 440], parameters: { httpMethod: 'POST', path: 'leadgen-competitors-poke', responseMode: 'onReceived' } }, output: [{ body: {} }] });

const claim = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Claim Competitors Work', position: [440, 320], executeOnce: true, parameters: { operation: 'executeQuery', query: "SELECT work_item_id, claim_token, service_run_id, campaign_id, campaign_lead_id FROM leadgen.claim_work_items('competitors', $1)", options: { queryReplacement: expr('competitors-{{ $execution.id }}') } }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ work_item_id: 'wi', claim_token: 'ct', campaign_id: 'c', campaign_lead_id: 'l' }] });

const getTarget = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Get Target', position: [700, 320], parameters: { operation: 'executeQuery', query: "SELECT b.id AS business_id, b.business_name, b.website_domain, b.address, b.lat, b.lng, b.place_id, c.business_type AS category, (SELECT e.value_jsonb #>> '{}' FROM leadgen.evidence_items e WHERE e.business_id=b.id AND e.campaign_id=cl.campaign_id AND e.feature_key='rating' ORDER BY e.observed_at DESC LIMIT 1) AS rating, (SELECT e.value_jsonb #>> '{}' FROM leadgen.evidence_items e WHERE e.business_id=b.id AND e.campaign_id=cl.campaign_id AND e.feature_key='review_volume' ORDER BY e.observed_at DESC LIMIT 1) AS review_volume FROM leadgen.campaign_leads cl JOIN leadgen.businesses b ON b.id=cl.business_id JOIN leadgen.campaigns c ON c.id=cl.campaign_id WHERE cl.id=$1", options: { queryReplacement: expr('{{ $json.campaign_lead_id }}') } }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ business_id: 'b', business_name: 'X', category: 'med spa', lat: 0, lng: 0, rating: '4.6', review_volume: '120' }] });

const placesNearby = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Places Nearby', position: [960, 320], onError: 'continueRegularOutput', retryOnFail: true, maxTries: 3, waitBetweenTries: 2500, parameters: { method: 'POST', url: 'https://places.googleapis.com/v1/places:searchText', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', sendHeaders: true, specifyHeaders: 'keypair', headerParameters: { parameters: [ { name: 'X-Goog-FieldMask', value: 'places.id,places.displayName,places.websiteUri,places.formattedAddress,places.rating,places.userRatingCount,places.primaryType' } ] }, sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr('={{ ($(\'Get Target\').item.json.lat && $(\'Get Target\').item.json.lng) ? { "textQuery": $(\'Get Target\').item.json.category, "locationBias": { "circle": { "center": { "latitude": Number($(\'Get Target\').item.json.lat), "longitude": Number($(\'Get Target\').item.json.lng) }, "radius": 8000 } }, "maxResultCount": 20 } : { "textQuery": ($(\'Get Target\').item.json.category + " near " + ($(\'Get Target\').item.json.address || "")), "maxResultCount": 20 } }}'), options: { timeout: 30000 } }, credentials: { httpHeaderAuth: newCredential('Google Places API') } }, output: [{ places: [] }] });

const rank = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Rank Competitors', position: [1200, 320], parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const T=$('Get Target').item.json; const resp=$json; const places=Array.isArray(resp.places)?resp.places:[]; function domainOf(u){ if(!u) return ''; var s=(''+u).toLowerCase().split('://').pop(); if(s.indexOf('www.')===0) s=s.slice(4); return s.split('/')[0]; } var tnm=((T.business_name||'')+'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\\s+/g,' ').trim(); var STOP={the:1,and:1,llc:1,inc:1,co:1,of:1,for:1}; var ttoks=tnm.split(' ').filter(function(w){ return w.length>=3 && !STOP[w]; }); function isTarget(nm,pid){ if(pid && T.place_id && pid===T.place_id) return true; var s=((nm||'')+'').toLowerCase(); if(!ttoks.length) return false; for(var i=0;i<ttoks.length;i++){ if(s.indexOf(ttoks[i])<0) return false; } return true; } var rows=[]; for(var i=0;i<places.length;i++){ var p=places[i]||{}; var nm=(p.displayName&&p.displayName.text)||''; var rc=p.userRatingCount||0; var rt=(p.rating!=null?p.rating:null); if(!nm||rt==null||rc<15) continue; if(isTarget(nm,p.id)) continue; rows.push({ place_id:p.id, name:nm, domain:domainOf(p.websiteUri), rating:rt, reviews:rc, address:p.formattedAddress||'' }); } rows.sort(function(a,b){ return (b.rating*Math.log(1+b.reviews)) - (a.rating*Math.log(1+a.reviews)); }); var best=rows[0]||null; var others=rows.slice(1,3).map(function(r){ return { name:r.name, rating:r.rating, reviews:r.reviews }; }); var tRating=(T.rating!=null&&T.rating!=='')?Number(T.rating):null; var tReviews=(T.review_volume!=null&&T.review_volume!=='')?Number(T.review_volume):null; return { json:{ hasBest:!!best, bestName:best?best.name:'', bestDomain:best?best.domain:'', bestAddress:best?best.address:'', best:best, others:others, target:{ rating:tRating, reviews:tReviews } } };" } }, output: [{ hasBest: true, bestName: 'X', bestDomain: 'x.com', bestAddress: 'St, City', best: {}, others: [], target: {} }] });

const compMeta = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Comp Meta', position: [1460, 200], onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 2000, parameters: { method: 'GET', url: 'https://graph.facebook.com/v21.0/ads_archive', sendQuery: true, specifyQuery: 'keypair', queryParameters: { parameters: [ { name: 'search_terms', value: expr("{{ $('Rank Competitors').item.json.bestName || 'zzzz' }}") }, { name: 'ad_reached_countries', value: '["US"]' }, { name: 'ad_active_status', value: 'ACTIVE' }, { name: 'fields', value: 'id,page_name,ad_snapshot_url' }, { name: 'limit', value: '10' }, { name: 'access_token', value: '<<META_TOKEN>>' } ] }, options: { timeout: 30000 } } }, output: [{ data: [] }] });

const compGoogle = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Comp Google', position: [1460, 380], onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 2500, parameters: { method: 'GET', url: 'https://serpapi.com/search.json', authentication: 'predefinedCredentialType', nodeCredentialType: 'serpApi', sendQuery: true, specifyQuery: 'keypair', queryParameters: { parameters: [ { name: 'engine', value: 'google_ads_transparency_center' }, { name: 'text', value: expr("{{ $('Rank Competitors').item.json.bestDomain || $('Rank Competitors').item.json.bestName || 'zzzz' }}") } ] }, options: { timeout: 30000 } }, credentials: { serpApi: newCredential('SerpApi account') } }, output: [{ ad_creatives: [] }] });

const compYelp = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Comp Yelp', position: [1460, 560], onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 2500, parameters: { method: 'GET', url: 'https://serpapi.com/search.json', authentication: 'predefinedCredentialType', nodeCredentialType: 'serpApi', sendQuery: true, specifyQuery: 'keypair', queryParameters: { parameters: [ { name: 'engine', value: 'yelp' }, { name: 'find_desc', value: expr("{{ $('Rank Competitors').item.json.bestName || 'zzzz' }}") }, { name: 'find_loc', value: expr("{{ $('Rank Competitors').item.json.bestAddress || 'United States' }}") } ] }, options: { timeout: 30000 } }, credentials: { serpApi: newCredential('SerpApi account') } }, output: [{ ads_results: [] }] });

const buildEvidence = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Build Competitor Evidence', position: [1720, 320], parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const R=$('Rank Competitors').item.json; const T=$('Get Target').item.json; const meta=$('Comp Meta').item.json||{}; const goog=$('Comp Google').item.json||{}; const yelp=$('Comp Yelp').item.json||{}; const best=R.best||null; var summary={ meta:'NONE', google:'NONE', yelp:'NONE' }; var confirmed=[]; var urls=[]; if(best){ var nm=((best.name||'')+'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\\s+/g,' ').trim(); var STOP={the:1,and:1,llc:1,inc:1,co:1,of:1,for:1}; var toks=nm.split(' ').filter(function(w){ return w.length>=3 && !STOP[w]; }); var matchName=function(t){ var s=((t||'')+'').toLowerCase(); if(!toks.length) return false; for(var i=0;i<toks.length;i++){ if(s.indexOf(toks[i])<0) return false; } return true; }; var mAds=Array.isArray(meta.data)?meta.data:[]; var mM=mAds.filter(function(a){ return a && matchName(a.page_name); }); if(mM.length){ summary.meta='CONFIRMED'; confirmed.push('Meta'); for(var i=0;i<mM.length && urls.length<2;i++){ if(mM[i].ad_snapshot_url) urls.push(mM[i].ad_snapshot_url); } } var gC=Array.isArray(goog.ad_creatives)?goog.ad_creatives:(Array.isArray(goog.ads)?goog.ads:[]); if(gC.length){ summary.google='CONFIRMED'; confirmed.push('Google Ads'); var gu=(goog.search_metadata&&(goog.search_metadata.google_ads_transparency_center_url||goog.search_metadata.url))||null; if(gu) urls.push(gu); } var yA=Array.isArray(yelp.ads_results)?yelp.ads_results:(Array.isArray(yelp.inline_ads)?yelp.inline_ads:[]); for(var y=0;y<yA.length;y++){ var ya=yA[y]||{}; if(matchName(ya.title||ya.name)){ summary.yelp='CONFIRMED'; confirmed.push('Yelp'); var yu=ya.link||ya.link_href||null; if(yu) urls.push(yu); break; } } } var cset={ generated_at:new Date().toISOString(), has_data:!!best, target:R.target||{ rating:null, reviews:null }, best: best?{ name:best.name, rating:best.rating, reviews:best.reviews, website:best.domain||null, ads:{ summary:summary, confirmed:confirmed, live_ad_urls:urls, is_advertising:confirmed.length>0 } }:null, others:(R.others||[]) }; const evidence=[ { feature_key:'competitor_set', value:cset, value_type:'object', product_tag:'ads_video', source_provider:'competitor_finder', idempotency_key:T.business_id+':competitor_set:comp-v1' } ]; return { json:{ payload:{ evidence:evidence, cause_type:'competitors_evidence', run:{ workflow_version:'comp-v1' } } } };" } }, output: [{ payload: {} }] });

const complete = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Complete Competitors', position: [1980, 320], parameters: { operation: 'executeQuery', query: "=SELECT leadgen.complete_analysis_work_item('{{ $('Claim Competitors Work').item.json.work_item_id }}'::uuid, '{{ $('Claim Competitors Work').item.json.claim_token }}'::uuid, '{{ JSON.stringify($json.payload).replace(/'/g, \"''\") }}'::jsonb) AS result" }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ result: {} }] });

const note = sticky('## Competitor Gap-Finder (warm-gated `competitors` service)\n\nClaim competitors -> Get Target (category + rating/reviews) -> Places Text Search (locationBias circle) -> Rank (exclude target, >=15 reviews, rating x ln(1+reviews); pick best + 2 runners-up) -> deep-dive the BEST rival (Meta + SerpApi Google/Yelp, all-token matcher) -> competitor_set evidence -> complete_analysis (cause competitors_evidence) -> re-score. Report renders "How you stack up". Warm-gated by the Scorer; behind service_config.competitors.enabled. Named-rival ad claims are CONFIRMED-only.', [claim], { color: 4 });

export default workflow('leadgen-competitors-gap', 'Leadgen — Competitor Gap-Finder')
  .add(everyMinute).to(claim)
  .add(poke).to(claim)
  .add(claim).to(getTarget).to(placesNearby).to(rank).to(compMeta).to(compGoogle).to(compYelp).to(buildEvidence).to(complete)
  .add(note);
