// Leadgen — Review Miner (US1 T037/T038). Deploy via create_workflow_from_code.
// Claims a 'reviews' work item -> Apify Google Maps reviews (newest ~150 via
// run-sync-get-dataset-items) -> Tier-1 deterministic stats (review_volume, rating,
// owner_response_rate, trajectory) -> Tier-2 Gemini theme extraction (4 product tags
// + complaint quotes) with a QUOTE-CHECKER (each quote must substring-match the
// review corpus, else dropped) -> typed evidence via complete_analysis_work_item.
// Degrades gracefully: Apify error -> still completes (no review evidence); Gemini
// error -> Tier-1 evidence still lands. Ephemeral corpus (FR-026): raw reviews are
// NOT persisted; only derived stats + verified short quotes.
// SECRETS: Apify token + Gemini key are in the request URLs (n8n DB); redacted to
// <<APIFY_TOKEN>> / <<GEMINI_KEY>> in git (use real values when validating/creating).
import { workflow, node, trigger, sticky, newCredential, expr } from '@n8n/workflow-sdk';

const everyMinute = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.3, config: { name: 'Poll Reviews Queue', position: [200, 240], parameters: { rule: { interval: [{ field: 'minutes', minutesInterval: 1 }] } } }, output: [{}] });
const poke = trigger({ type: 'n8n-nodes-base.webhook', version: 2.1, config: { name: 'Reviews Poke', position: [200, 440], parameters: { httpMethod: 'POST', path: 'leadgen-reviews-poke', responseMode: 'onReceived' } }, output: [{ body: {} }] });

const claim = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Claim Reviews Work', position: [460, 320], executeOnce: true, parameters: { operation: 'executeQuery', query: "SELECT work_item_id, claim_token, service_run_id, campaign_id, campaign_lead_id FROM leadgen.claim_work_items('reviews', $1)", options: { queryReplacement: expr('reviews-{{ $execution.id }}') } }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ work_item_id: 'wi', claim_token: 'ct', campaign_id: 'c', campaign_lead_id: 'l' }] });

const getTarget = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Get Target', position: [700, 320], parameters: { operation: 'executeQuery', query: "SELECT b.id AS business_id, b.place_id, b.business_name FROM leadgen.campaign_leads cl JOIN leadgen.businesses b ON b.id=cl.business_id WHERE cl.id=$1", options: { queryReplacement: expr('{{ $json.campaign_lead_id }}') } }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ business_id: 'b', place_id: 'ChIJ...', business_name: 'Spa' }] });

// Apify: run-sync-get-dataset-items returns the reviews array; fullResponse keeps it
// as ONE item ($json.body = [...]) so downstream aggregates in a single pass and the
// empty/error case still yields one item (no stuck work item).
const fetchReviews = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Fetch Reviews', position: [940, 320], onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 5000, parameters: { method: 'POST', url: 'https://api.apify.com/v2/acts/compass~google-maps-reviews-scraper/run-sync-get-dataset-items?token=<<APIFY_TOKEN>>&timeout=200', sendBody: true, specifyBody: 'json', jsonBody: expr('={ "placeIds": ["{{ $json.place_id }}"], "maxReviews": 150, "reviewsSort": "newest", "language": "en" }'), options: { timeout: 230000, response: { response: { fullResponse: true } } } } }, output: [{ body: [{ text: 'great', stars: 5 }] }] });

const computeStats = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Compute Review Stats', position: [1180, 320], parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const resp=$json; const reviews = Array.isArray(resp.body)?resp.body:(Array.isArray(resp)?resp:[]); const n=reviews.length; const num=x=>typeof x==='number'&&isFinite(x); let placeRating=null, placeCount=null; if(n>0){ placeRating = num(reviews[0].totalScore)?reviews[0].totalScore:null; placeCount = num(reviews[0].reviewsCount)?reviews[0].reviewsCount:null; } const stars=reviews.map(r=>r.stars).filter(num); const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null; const avgStars=avg(stars); const withResp=reviews.filter(r=>r.responseFromOwnerText && (''+r.responseFromOwnerText).trim()).length; const ownerRate = n? +(withResp/n).toFixed(3):null; const third=Math.max(1,Math.floor(stars.length/3)); const traj=(stars.length>=3)? +((avg(stars.slice(0,third))||0)-(avg(stars.slice(-third))||0)).toFixed(2):null; const texts=reviews.map(r=>(r.text||'').replace(/\\s+/g,' ').trim()).filter(Boolean); const corpus=texts.join(' || ').toLowerCase(); const sample=texts.slice(0,60).map((t,i)=>'['+i+'] '+t.slice(0,400)).join('\\n'); const prompt='You are analyzing customer reviews of a local business ('+($('Get Target').item.json.business_name||'')+') to find sales angles for four products: voice_ai (phone/scheduling/booking pain, missed calls, hold times, no callback), web_seo (website/online-presence complaints), ads_video (visibility/reputation), consulting (operational/staffing/process issues). Return ONLY compact JSON: {themes:[{product_tag, theme (short), severity (low|med|high), quotes:[...]}], phone_scheduling_complaint_reviews: <int count of reviews mentioning phone/scheduling/booking problems>, total_complaint_reviews: <int>}. CRITICAL for quotes: each quote MUST be a short phrase (5 to 15 words) copied CHARACTER-FOR-CHARACTER verbatim from a review below (do NOT paraphrase, summarize, or fix grammar). If you cannot find an exact verbatim phrase for a theme, use an empty quotes array. Reviews:\\n'+sample; const geminiBody={ contents:[{parts:[{text:prompt}]}], generationConfig:{responseMimeType:'application/json', maxOutputTokens:1200, thinkingConfig:{thinkingBudget:0}} }; return { json:{ n_reviews:n, review_volume: placeCount!=null?placeCount:n, rating: placeRating!=null?placeRating:avgStars, owner_response_rate: ownerRate, trajectory: traj, corpus, has_reviews: n>0, geminiBody } };" } }, output: [{ n_reviews: 150, review_volume: 584, rating: 5, owner_response_rate: 0.3, geminiBody: {} }] });

const extractThemes = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Extract Themes', position: [1420, 320], onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 5000, parameters: { method: 'POST', url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=<<GEMINI_KEY>>', sendBody: true, specifyBody: 'json', jsonBody: expr('={{ $json.geminiBody }}'), options: { timeout: 60000, batching: { batch: { batchSize: 1, batchInterval: 2500 } } } } }, output: [{ candidates: [] }] });

const buildEvidence = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Build Reviews Evidence', position: [1660, 320], parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const stats=$('Compute Review Stats').item.json; const vis=$json; const claim=$('Claim Reviews Work').item.json; const tgt=$('Get Target').item.json; const cid=claim.campaign_id, bid=tgt.business_id; function mk(fk,val,vt,unit,tag){ return {feature_key:fk,value:val,value_type:vt,unit:unit,product_tag:tag,source_provider:'review_miner',idempotency_key:cid+':'+bid+':'+fk}; } const ev=[]; if(stats.review_volume!=null) ev.push(mk('review_volume',stats.review_volume,'integer','count','ads_video')); if(stats.rating!=null) ev.push(mk('rating',stats.rating,'decimal',null,'ads_video')); if(stats.owner_response_rate!=null){ ev.push(mk('owner_response_rate',stats.owner_response_rate,'decimal',null,'voice_ai')); ev.push(mk('owner_responds_to_reviews', stats.owner_response_rate>=0.2, 'boolean', null,'consulting')); } if(stats.trajectory!=null) ev.push(mk('review_trajectory',stats.trajectory,'decimal',null,'ads_video')); let v={}; try{ let raw=''; const cand=vis&&vis.candidates&&vis.candidates[0]; if(cand&&cand.content&&cand.content.parts&&cand.content.parts[0]) raw=(cand.content.parts[0].text||'').toString().trim(); raw=raw.split('```json').join('').split('```').join('').trim(); const m=raw.match(/\\{[\\s\\S]*\\}/); if(m) raw=m[0]; v=JSON.parse(raw); }catch(e){ v={}; } const corpus=stats.corpus||''; function verify(q){ if(!q) return false; const s=(''+q).replace(/\\s+/g,' ').trim().toLowerCase(); if(s.length<12) return false; if(corpus.indexOf(s)!==-1) return true; const w=Math.min(s.length,45); for(let i=0;i+w<=s.length;i+=8){ if(corpus.indexOf(s.substr(i,w))!==-1) return true; } return false; } let verifiedThemes=[]; if(Array.isArray(v.themes)){ for(const th of v.themes){ const vq=(th.quotes||[]).filter(verify).slice(0,3); verifiedThemes.push({product_tag:th.product_tag, theme:th.theme, severity:th.severity, quotes:vq, quote_verified: vq.length>0}); } } if(stats.n_reviews>0 && (v.phone_scheduling_complaint_reviews!=null)){ const share=Math.max(0,Math.min(1, (Number(v.phone_scheduling_complaint_reviews)||0)/stats.n_reviews)); ev.push(mk('phone_complaint_share', +share.toFixed(3), 'decimal', null, 'voice_ai')); } if(verifiedThemes.length){ ev.push({feature_key:'complaint_themes', value:{ themes:verifiedThemes, total_complaint_reviews:v.total_complaint_reviews??null, n_reviews:stats.n_reviews }, value_type:'object', product_tag:'voice_ai', source_provider:'review_miner', idempotency_key:cid+':'+bid+':complaint_themes', excerpt:(verifiedThemes.filter(t=>t.quotes.length).map(t=>t.theme).slice(0,3).join('; ')).slice(0,500)}); } return { json:{ payload:{ cause_type:'reviews_evidence', evidence:ev, run:{ workflow_version:'review-miner-v1' } } } };" } }, output: [{ payload: {} }] });

const complete = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Complete Reviews', position: [1900, 320], parameters: { operation: 'executeQuery', query: "SELECT leadgen.complete_analysis_work_item('{{ $('Claim Reviews Work').item.json.work_item_id }}'::uuid, '{{ $('Claim Reviews Work').item.json.claim_token }}'::uuid, '{{ JSON.stringify($json.payload).replace(/'/g, \"''\") }}'::jsonb) AS result", options: {} }, credentials: { postgres: newCredential('Postgres account') } }, output: [{ result: {} }] });

const note = sticky('## Review Miner (US1 T037/T038)\n\nApify newest-150 -> Tier-1 deterministic stats (review_volume, rating, owner_response_rate, trajectory) -> Tier-2 Gemini theme extraction (4 product tags + complaint quotes) with a quote-checker (verbatim substring match vs corpus, else dropped) -> typed evidence. Ephemeral corpus (FR-026): raw reviews never persisted, only derived stats + verified short quotes. Degrades: Apify error -> completes with no review evidence; Gemini error -> Tier-1 still lands.', [claim], { color: 5 });

export default workflow('leadgen-review-miner', 'Leadgen — Review Miner')
  .add(everyMinute).to(claim)
  .add(poke).to(claim)
  .add(claim).to(getTarget).to(fetchReviews).to(computeStats).to(extractThemes).to(buildEvidence).to(complete)
  .add(note);
