-- human_actions.sql (T024)
-- issue_approval_token, record_approval (locked one-time consumption),
-- record_sales_status, record_lead_disposition, record_suppression.
-- Granted ONLY to the human-actions role (100_privileges.sql).

CREATE OR REPLACE FUNCTION @@SCHEMA@@.issue_approval_token(
  p_campaign_id uuid, p_issued_to text, p_raw_token text, p_ttl interval DEFAULT '12 hours')
RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, @@SCHEMA@@ AS $$
DECLARE v_id uuid;
BEGIN
  -- raw token is generated by the workflow (cryptographically random) and only
  -- its hash is stored; the raw value travels in the signed link once.
  INSERT INTO approval_tokens (campaign_id, token_hash, issued_to, expires_at)
  VALUES (p_campaign_id, encode(sha256(p_raw_token::bytea),'hex'), p_issued_to, now() + p_ttl)
  RETURNING id INTO v_id;
  RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.record_approval(
  p_raw_token text, p_decision text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, @@SCHEMA@@ AS $$
DECLARE t approval_tokens; c campaigns;
BEGIN
  IF p_decision NOT IN ('approved','rejected') THEN
    RAISE EXCEPTION 'invalid_request' USING ERRCODE='P0001';
  END IF;
  SELECT * INTO t FROM approval_tokens
   WHERE token_hash = encode(sha256(p_raw_token::bytea),'hex') FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('status','unknown_token'); END IF;
  IF t.used_at IS NOT NULL  THEN RETURN jsonb_build_object('status','already_used'); END IF;
  IF t.revoked_at IS NOT NULL THEN RETURN jsonb_build_object('status','revoked'); END IF;
  IF t.expires_at <= now()  THEN RETURN jsonb_build_object('status','expired'); END IF;

  SELECT * INTO c FROM campaigns WHERE id = t.campaign_id FOR UPDATE;
  IF c.status IN ('complete','failed','canceled','finalizing') THEN
    RETURN jsonb_build_object('status','campaign_terminal');
  END IF;

  UPDATE approval_tokens SET used_at = now(), decision = p_decision WHERE id = t.id;
  UPDATE campaigns SET
    approval_status = p_decision,
    status = CASE WHEN status = 'awaiting_approval' THEN 'analyzing' ELSE status END,
    campaign_state_revision = campaign_state_revision + 1
  WHERE id = c.id;

  IF p_decision = 'approved' THEN
    UPDATE work_items SET state = 'pending', available_at = now()
     WHERE campaign_id = c.id AND service = 'enrichment' AND state = 'waiting_approval';
    PERFORM _emit_event('approval.granted','state_change', true, c.id, NULL,
      '{}'::jsonb, 'approval.granted:' || c.id);
  ELSE
    UPDATE work_items SET state = 'skipped_gate'
     WHERE campaign_id = c.id AND service = 'enrichment'
       AND state IN ('waiting_approval','blocked','pending');
    PERFORM _emit_event('approval.rejected','state_change', true, c.id, NULL,
      '{}'::jsonb, 'approval.rejected:' || c.id);
  END IF;
  RETURN jsonb_build_object('status','recorded','decision', p_decision);
END $$;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.record_sales_status(
  p_business_id uuid, p_sales_status text, p_changed_by text, p_reason text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, @@SCHEMA@@ AS $$
BEGIN
  INSERT INTO business_sales_state (business_id, sales_status, changed_by, reason)
  VALUES (p_business_id, p_sales_status, p_changed_by, p_reason);
  UPDATE businesses SET sales_status = p_sales_status, last_updated = now()
   WHERE id = p_business_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'unknown_business' USING ERRCODE='P0001'; END IF;
  RETURN jsonb_build_object('status','recorded');
END $$;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.record_lead_disposition(
  p_campaign_lead_id uuid, p_outcome text, p_reviewed_by text, p_rejection_reason text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, @@SCHEMA@@ AS $$
BEGIN
  INSERT INTO campaign_lead_dispositions
    (campaign_lead_id, outcome, reviewed_by, rejection_reason)
  VALUES (p_campaign_lead_id, p_outcome, p_reviewed_by, p_rejection_reason);
  RETURN jsonb_build_object('status','recorded');
END $$;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.record_suppression(
  p_level text, p_value text, p_reason text, p_idempotency_key text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, @@SCHEMA@@ AS $$
BEGIN
  INSERT INTO suppressions (level, value, reason, idempotency_key)
  VALUES (p_level, lower(p_value), p_reason, p_idempotency_key)
  ON CONFLICT (idempotency_key) DO NOTHING;
  RETURN jsonb_build_object('status','recorded');
END $$;
